### ISSUE TITLE
Merge, both ways, features with https://github.com/sbidin/sdl2-ttf

### ISSUE THREAD

**Issue by Mikolaj** [haskell-game/sdl2-ttf#2]
I'm thinking short term, as a user: I need the best of both worlds.

I need the breadth of bindings coverage and the good character translation implementation of https://github.com/sbidin/sdl2-ttf (see my remarks and links at https://github.com/rongcuid/sdl2-ttf/pull/4#issuecomment-304550790) 

But I also need the various fixes of this very repo (I've already contributed some as pull requests to https://github.com/sbidin/sdl2-ttf) and probably a feature or two as well (didn't look closely enough).

Finally, I need this package on Hackage so that people can build my game directly from Hackage and so that hydra.nixos.org can build it automatically just with cabal.

**Comment by Mikolaj** [comment]
@sbidin: please join the discussion and I'm sorry for discovering you so late --- I only searched Hackage and your package is not there :(

**Comment by sbidin** [comment]
Hi Mikolaj, no worries, I purposefully didn't place sdl2-ttf on Hackage due to there already being an existing and used version online. I'd love to see someone do a merge into haskell-game/sd2-ttf.

**Comment by Mikolaj** [comment]
If any of you is at ZuriHack, I've announced this project (PR that merges the 2 bindings), so perhaps we could hack on it together: https://zurihac.info/#projects  :)

**Comment by ocharles** [comment]
I'll be there and would be happy to do some `sdl2` stuff :)

**Comment by Mikolaj** [comment]
A question emerged: can we get away with unsafe foreign imports?

I think the code for generating foreign imports in @sbidin /sdl2-ttf is better and more in line with other SDL2 packages. However, it uses safe foreign imports (just as the core SDL2 bindings do), which are probably much slower in this case, while the current haskell-game/sdl2-ttf uses unsafe imports and they work fine in it.

I talked with @ocharles and I asked Ed Kmett, who created the gl bindings, and it seems in gl (and probably in sdl, when turning on debugging) safe bindings are needed in order to handle the debug callbacks to Haskell, and callbacks require safe imports. However, I think the Freetype library doesn't do debug callbacks (not sure), or at least SDL_ttf does not propagate them, so we should be fine with unsafe imports.

If you agree unsafe imports are in fact OK in this case, my plan would be to use the TH for foreign imports from sbidin/sdl2-ttf and after merging that in, create another commit that turns this to unsafe imports and then test under Linux and Windows. 

In fact, I would probably use most of the other code and the complete API from sbidin/sdl2-ttf as well, because it seems more in sync with the core SDL2 bindings wrt naming, conventions, etc. That unfortunately means almost all functions names would change wrt haskell-game/sdl2-ttf. :( There is not a lot of them, though, so a few query-replaces should be almost enough to port code to the new API and we would at least keep compatibility with one of the two APIs. I'm still comparing the semantic differences between the packages...

Please let me know what you think.

**Comment by polarina** [comment]
@Mikolaj The runtime does full stop-the-world collections from time to time. It is important, especially for games, that the latency of stop-the-world collections are minimized as much as possible.

Stopping the world involves having all capabilities stop executing useful code. Unfortunately, the runtime can't preempt a call through an unsafe FFI import -- all capabilities will block until the call finishes, increasing the GC latency by as much as the duration of the call.

Any OpenGL function may flush the internal command queue to the GPU, which is not a cheap operation. That's why they're all marked as `safe` imports.

Many SDL2 functions can block and execute for a long time as well. Some are very cheap and could as well have been marked as `unsafe` -- looking through the C source and determining for each function if they are potentially blocking or not is just a lot of work that I hadn't gotten around doing. :)

**Comment by Mikolaj** [comment]
@polarina: ok, thank you for the tips; so, for now, I don't propose to make any imports unsafe in sdl-ttf as well.
